name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install winres
        run: go install github.com/tc-hib/go-winres@latest

      - name: Build winres files
        run: go-winres make

      - name: Build executable
        run: go build -v .
